### PR TITLE
Added api-lint checks

### PR DESCRIPTION
**Pull request by azizbekxm**
## Purpose
acq-modules need other api-link checks

https://github.com/folio-org/acq-models/pull/455 I missed "," after isBound and all tests are passed

and found error in mod-orders pr

decieded to add other checks currently there is only one check
https://github.com/folio-org/acq-models/tree/master/.github/workflows acq-models
https://github.com/folio-org/mod-orders/tree/master/.github/workflows mod-orders
## Approach
copied api-lint from mod-orders

### CODE REVIEW

**Review by SerhiiNosko — APPROVED** [review]

**Comment by dcrossleyau** [comment]
But why? I do not know what you are trying to achieve.
There are no RAML files in the "acq-models" GitHub repository for "api-lint" to act upon.

**Comment by azizbekxm** [comment]
> But why? I do not know what you are trying to achieve. There are no RAML files in the "acq-models" GitHub repository for "api-lint" to act upon.

https://github.com/folio-org/acq-models/pull/455 I missed "," after isBound and all tests are passed

image

and found error in mod-orders pr

image

There is .sample files need to be check as well

**Comment by dcrossleyau** [comment]
The purpose of "api-lint" is to verify API description files as RAML or OAS, and to verify examples against their API schema. Its task is not to find broken JSON files.

**Comment by azizbekxm** [comment]
> The purpose of "api-lint" is to verify API description files as RAML or OAS, and to verify examples against their API schema. Its task is not to find broken JSON files.
 
it is enought for acq-models
these failed api-lint check should fail as well in case of syntax error in .samples

**Comment by azizbekxm** [comment]
> > The purpose of "api-lint" is to verify API description files as RAML or OAS, and to verify examples against their API schema. Its task is not to find broken JSON files.
> 
> Do you mean it is not help to indetify syntax error

If you believe so, you can close comment

**Comment by azizbekxm** [comment]
> The purpose of "api-lint" is to verify API description files as RAML or OAS, and to verify examples against their API schema. Its task is not to find broken JSON files.

Is there any way to check these syntax error in .sample files?

**Comment by dcrossleyau** [comment]
You would need to create a new separate GitHub Workflow that finds and assesses those files.

**Pull request closed without merging**
