### PR TITLE
Move acquisitions-unit schemas/samples to acquisitions-unit folder

### PR DESCRIPTION
**Pull request by javalkar-varun**
## Purpose

Move acquistions-unit schemas/samples to acquisitions-unit

## Approach

- This came up while working on [MODINVOICE-69](https://issues.folio.org/browse/MODINVOICE-69). acquisitions-unit schemas will also be referred by mod-invoice. As a result, move them to acquisitions-unit folder so they can be accessed by mod-orders and mod-invoice.

#### TODOS
Needs to be merged with:
mod-orders - [PR#205](https://github.com/folio-org/mod-orders/pull/205)
mod-orders-storage - [PR#147](https://github.com/folio-org/mod-orders-storage/pull/147)

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.

- Does this PR meet or exceed the expected quality standards?
  - [x] Examples exist for all schemas
  - [x] Descriptions exist for all schema properties
  - [x] All schemas pass raml-cop linting
- Does this introduce breaking changes?
  - [x] Were there any schema changes?
  - [ ] There are no breaking changes in this PR.
  
If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?  
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.  

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

### CODE REVIEW

**Comment by javalkar-varun** [comment]
I have linked PRs to update raml for mod-orders/orders-storage above.

**Comment by javalkar-varun** [comment]
Valid point but thinking ahead, as finance module evolves, acquisition units will be `$ref` by different finance schemas. So, it makes sense to move them to a `common` folder now rather than doing it later.

**Comment by pautau-s** [comment]
@javalkar-varun I may have missed something. How exactly will acquisition units will be `$ref` in finance schemas?

**Comment by javalkar-varun** [comment]
On a high level, that's what my understanding is. For specifics, maybe @craigmcnally can chime in.

**Comment by craigmcnally** [comment]
Sorry for the confusion guys.  I've been looking at way too many schemas lately 😕

**Pull request merged**
